### ISSUE TITLE
Switch Trigger Implementation

### ISSUE THREAD

**Issue by jens-erdmann** [oss-review-toolkit/ort-ci-gitlab#15]
Since GitLab version 14.9 the pipeline trigger implementation got expanded by the [strategy](https://docs.gitlab.com/ee/ci/yaml/#triggerstrategy) keyword. To my understanding this could replace the polling logic implemented in [ort-gitlab-ci.yml](https://github.com/oss-review-toolkit/ort-gitlab-ci/blob/main/ort-gitlab-ci.yml) ,

**Comment by jens-erdmann** [comment]
[ort-gitlab-ci.yml line 93](https://github.com/oss-review-toolkit/ort-gitlab-ci/blob/main/ort-gitlab-ci.yml#L93)
```
# # The 'nice' way of triggering downstream pipeline is commented out
# # because it's not possible to retrieve back artifacts this way.
```

I assume this statement is still valid.

**Comment by tsteenbe** [comment]
@jens-erdmann  Yes the comment is still valid, @zhernovs could you maybe add a link to the comment [ort-gitlab-ci.yml line 93](https://github.com/oss-review-toolkit/ort-gitlab-ci/blob/main/ort-gitlab-ci.yml#L93) so people can see we are not the only ones with this issue?

**Comment by zhernovs** [comment]
Correct, the situation hasn't changed for about two years. 
https://gitlab.com/gitlab-org/gitlab/-/issues/284085
Let me add this to comment.
