### ISSUE TITLE
Error in ORT_RESULTS_SCANNER_FILE configuration

### ISSUE THREAD

**Issue by awischnewski** [oss-review-toolkit/ort-ci-gitlab#20]
It seems the specification of the ORT_RESULTS_SCANNER_FILE variable is incorrect, which leads to empty web reports in case the evaluater is disabled. 

https://github.com/driveblocks/ort-gitlab-ci/blob/main/.gitlab-ci.yml#L166

In addition, we faced the challenge that the ORT_DISABLE_ADVISOR, ORT_DISABLE_EVALUATOR and ORT_DISABLE_SCANNER variables have to be set explicitly to false for the toolkit to work correctly. This is hard to grasp from the description of the variables as they do not have a default value. 

I'll prepare a pull request to propose a fix for both topics.

**Comment by sschuberth** [comment]
I believe this has been fixed with the recent merges; in any case, we're going to deprecate / archive this project soon in favor of another GitLab integration approach. So I'm closing this.
