### ISSUE TITLE
Stage to build and tag docker image

### ISSUE THREAD

**Issue by dancunogenda-omondi** [oss-review-toolkit/ort-ci-gitlab#28]
What exactly is missing from this job when run from GitLab CI. The dockerfile is first build and tagged with $CI_REGISTRY/ort:latest. SO when the job is being run, it will use that cache. It however still compains about #ERROR: invalid tag "/ort:c1c053e": invalid reference format. Any solutions to this

**Comment by tsteenbe** [comment]
Thank you for your issue @dancunogenda-omondi  and sorry for only now getting back to you - was dealing with family health issues resulting me in not working on ORT for a long time. I have rewritten the integration in this repository to now use [official ORT docker image](https://github.com/oss-review-toolkit/ort/pkgs/container/ort) so no need to build the Docker image yourself anymore making this issue no longer relevant so I am closing it now.

**Comment by dancunogenda-omondi** [comment]
Nice to see you back and hope everything is well. Thanks for updating the problem and fixing it
