### ISSUE TITLE
In general I would suggest you delete this project and push a docker image to docker hub which can be used

### ISSUE THREAD

**Issue by ReXtrem** [oss-review-toolkit/ort-ci-gitlab#30]
Imagine following gitlab-ci:

```
compliance:ort:
  stage: compliance
  image: ort-analyzer:1.2.3
  variables:
      INPUT_DIR: $CI_PROJECT_DIR
      OUTPUT_DIR: $CI_PROJECT_DIR/ort-output
      FORMAT : JSON
  script:
    - ort analyze -i $INPUT_DIR -o $OUTPUT_DIR -f $FORMAT --info
```

The solution provided on this project is overcomplicated as fuck to be honest

**Comment by tsteenbe** [comment]
@ReXtrem Please have a look at the current version.  I pushed a rewrite of the GitLab pipeline 2 weeks ago which uses the ORT docker image which should be a powerful yet a lot easier to use. Our users contain a lot of non-technical users (read lawyer/compliance folks) so we need to find a balance between easy of use and being able to use ORT in a way that works for the user's way of working.

**Comment by tsteenbe** [comment]
Closing this old issue, ORT Docker image is available from GitHub see https://github.com/oss-review-toolkit/ort/pkgs/container/ort
