### ISSUE TITLE
Link in README doesn't work

### ISSUE THREAD

**Issue by brytannia** [oss-review-toolkit/ort-ci-gitlab#4]
I'm following instructions in the README and I can't open a link for [ORT configuration repo](https://gitlab.com/tsteenbe/ort-configuration). I get an error 404. Probably, this repository is not public. However, seems that this link is redundant as I was able to set up the scanning job without this repo.

**Comment by tsteenbe** [comment]
@brytannia  I have updated the link in the README and ORT for GitLab's code to use the [official ORT configuration](https://github.com/oss-review-toolkit/ort-config).
